SELECT * FROM payment WHERE TYPE_ID = (SELECT ID FROM PAYMENTTYPE WHERE NAME = 'MONTHLY');
SELECT * FROM mark WHERE SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE NAME = 'Art');
SELECT DISTINCT (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID) FROM STUDENT RIGHT JOIN payment ON student.id = payment.student_id WHERE PAYMENT.TYPE_ID = (SELECT id FROM paymenttype WHERE name = 'WEEKLY');
SELECT (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID, STUDENT.BIRTHDAY) FROM STUDENT INNER JOIN mark ON student.id = mark.student_id WHERE SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE SUBJECT.NAME = 'Math');